package by.derovi.botp2p.exchange

enum class PaymentMethod(val readableName: String) {
    AK_BARS_BANK(""),
    ALFA_BANK(""),
    ADV_CASH(""),
    FPS(""),
    MKB(""),
    HOMECREDIT(""),
    SPORTBANK(""),
    AVANGARD(""),
    PARITETBANK(""),
    MTBANK(""),
    MOSCOW_BANK(""),
    RNKB(""),
    ABSOLUTBANK(""),
    PERFECT_MONEY(""),
    BANK_TRANSFER("Банковский перевод"),
    TINKOFF("Тинькофф"),
    SOVCOMBANK(""),
    PSB(""),
    SBP_TRANSFER(""),
    VTB("ВТБ"),
    ROSBANK("Росбанк"),
    RAIFAIZEN("Райффайзенбанк"),
    ROSSELHOZBANK("Россельхозбанк"),
    ROCKETBANK(""),
    QIWI("QIWI"),
    BINANCEPAY("BinancePay (RUB)"),
    SBERBANK("Сбербанк"),
    POSTBANK("Почта банк"),
    PAYEER("Payeer"),
    MTSBANK("МТС-Банк"),
    RUSSIANSTANDARD("Русский Стандарт"),
    OTPBANK("ОПТ Банк"),
    OTKRITIE("Банк Открытие"),
    UNICREDIT("Юникредит"),
    CITIBANK("Ситибанк"),
    BCSBANK("БЦСБанк"),
    YANDEXMONEY("ЮМани"),
    URALSIB("Уралсиб Банк"),
    GAZPROMBANK("Газпромбанк")
}